config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'pages#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :batches
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_line_items, dependent: :delete_all
  has_many :quantities, through: :recipe_line_items
  has_many :ingredients, through: :recipe_line_items
  has_many :batches, dependent: :delete_all

  accepts_nested_attributes_for :recipe_line_items, reject_if: :all_blank, allow_destroy: true

  before_validation :strip_whitespace
  validates :title, :description, presence: true

  private
    def strip_whitespace
      [title, description].each { |attr| attr.strip! unless attr.nil? }
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user

  def index
    @recipes = current_user.recipes.all.order(created_at: :desc)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    if @recipe.save
      flash[:info] = 'Recipe added'
      redirect_to recipe_path(@recipe)
    else
      flash[:error] = 'Womp womp...'
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = 'Recipe updated'
      redirect_to edit_recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:success] = 'Recipe deleted'
      redirect_to recipes_path
    else
      flash.now[:error] = 'Unable to delete'
      render 'edit'
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(
        :title,
        :description,
        recipe_line_items_attributes: [
          :id,
          :concentration_variable,
          :_destroy,
          quantity_attributes: [:unit, :amount],
          ingredient_attributes:[:name]
        ])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def recipe_ingredient_line_item(recipe_line_item)
    [recipe_line_item.ingredient.name, ' - ', recipe_line_item.quantity.amount, recipe_line_item.quantity.unit].reject(&:blank?).join(' ')
  end
end

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe, local: true,  html: { class: 'recipe-form' } ) do |recipe_form| %>
  <%= render 'shared/error_messages', object: recipe_form.object %>

  <%= recipe_form.input :title %>

  <%= recipe_form.input :description, as: :text, input_html: { rows: 4 } %>

  <h3>Ingredients</h3>
  <%= recipe_form.simple_fields_for :recipe_line_items do |line_item_form| %>
    <%= render 'recipe_line_item_fields', f: line_item_form %>
  <% end %>


  <div><%= link_to_add_association 'Add ingredient', recipe_form, :recipe_line_items %></div>
  <br>
  <%= recipe_form.submit 'Submit', class: 'btn btn-primary' %>
  <%= link_to('delete', @recipe, method: :delete, data: { confirm: 'You sure?' }, class: "btn btn-danger") if current_user.recipes.include?(@recipe) %>
<% end %>

app/views/recipes/_recipe_line_item_fields.html.erb
<div class="nested-fields">
  <div class="field control-group">
    <hr>
    <div class="controls form-inline">

      <% f.object.build_ingredient if f.object.ingredient.nil? %>
      <%= f.simple_fields_for :ingredient do |ingredient_form| %>
        <%= ingredient_form.input :name, label: false, placeholder: 'Ingredient name', input_html: { class: 'nested-ingredient'} %>
      <% end %>

      <% f.object.build_quantity if f.object.quantity.nil? %>
      <%= f.simple_fields_for :quantity do |quantity_form| %>
        <%= quantity_form.input :unit, as: :select, collection: quantity_form.object.unit_options_for_select, include_blank: 'Select Unit', label: false, input_html: { class: 'nested-ingredient recipe-select'}  %>
        <%= quantity_form.input :amount, label: false, placeholder: 'Amount as decimal', as: :decimal, input_html: { class: 'nested-ingredient'}  %>
      <% end %>

      <%= f.input :concentration_variable, label: 'Concentration Variable?', as: :select, input_html: { class: 'nested-ingredient recipe-select'}  %>

    </div>

    <%= link_to_remove_association 'Remove ingredient', f, data: { confirm: 'Are you sure?' } %>
    <!-- This confirmation code is not working in the current version of cocoon -->
  </div>
</div>

app/views/recipes/edit.html.erb
<% provide(:title, 'Edit Recipe') %>
<div class="row">
  <h1>Edit Recipe</h1>
  <%= link_to 'Back to recipe', recipe_path(@recipe) %>
  <%= render partial: 'form' %>
</div>

app/views/recipes/index.html.erb
<% provide(:title, 'Recipes') %>
<h1>Recipes</h1>
<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <%= link_to recipe.title, recipe_path(recipe) %>
    </li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<% provide(:title, 'New Recipe') %>
<h1>New Recipe</h1>
<%= render partial: 'form' %>

app/views/recipes/show.html.erb
<% provide(:title, 'Recipe') %>

<h3><%= @recipe.title %></h3>
<p class='text-muted'>This is a base recipe - think of it as x1. To create different size yields or concentrations, create a <%= link_to "new <i>Batch</i>".html_safe, new_recipe_batch_path(@recipe) %></p>
<strong>Description</strong>
<p><%= @recipe.description %></p>
<strong>Ingredients</strong>
<ul class="list-unstyled">
  <% @recipe.recipe_line_items.each do |recipe_line_item| %>
  <li>
    <div>
      <%= recipe_ingredient_line_item(recipe_line_item) %>
    </div>
  </li>
  <% end %>
</ul>
<div><%= link_to 'Edit', edit_recipe_path(@recipe) %></div>
<div><%= link_to "Create New Batch of #{@recipe.title}", new_recipe_batch_path(@recipe) %></div>
<div><%= link_to("Work with batches of #{@recipe.title}", recipe_batches_path(@recipe)) if @recipe.batches.any? %></div>

<% if @recipe.batches.any? %>
  <h3>Batches of this recipe</h3>
  <ul class="list-unstyled">
    <% @recipe.batches.order(updated_at: :desc).each do |batch| %>
      <li>
        <%= link_to batch.display_name(truncate_by: 50), recipe_batch_path(@recipe, batch) %>
      </li>
    <% end %>
  </ul>
<% end %>