config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'pages#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :batches
  end

end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :recipe
  has_many :recipe_line_items
  has_many :recipe_line_items, through: :recipe
  validates_associated :recipe
  validates :name, :prep_date, presence: true

  def date_mm_dd_yyyy
    prep_date.strftime("%m/%d/%Y") if prep_date?
  end

  def date_short
    prep_date.strftime("%b %d, '%y") if prep_date?
  end

  def date_long
    prep_date.strftime("%B %e, %Y") if prep_date?
  end

  def display_name(truncate_by: 25)
    [date_mm_dd_yyyy, name.truncate(truncate_by)].reject(&:blank?).join(' - ')
  end

  def concentration_percent
    concentration / 100.00
  end

end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :logged_in_user

  def index
    @recipe = Recipe.find(params[:recipe_id])
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])
    @batch = Batch.find(params[:id])
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @batch = @recipe.batches.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @batch = @recipe.batches.create(batch_params)
    if @batch.save
      flash[:info] = "Batch created for #{@recipe.title}"
      redirect_to recipe_batch_path(@recipe, @batch)
    else
      flash[:error] = 'Womp womp...'
      render :new
    end
  end

  def edit
    @batch = Batch.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def update
    @batch = Batch.find(params[:id])
    if @batch.update(batch_params)
      flash[:info] = "Batch updated for #{@batch.recipe.title}"
      redirect_to recipe_batch_path
    else
      flash[:error] = 'Womp womp...'
      render :new
    end
  end

  def destroy
    batch = Batch.find(params[:id])
    recipe = Recipe.find(params[:recipe_id])
    if batch.destroy
      flash[:info] = "Batch deleted!!!"
      redirect_to recipe_batches_path(recipe)
    else
      flash[:error] = 'Something went wrong'
      render recipe_batch_path(recipe)
    end
  end

    private

    def batch_params
      params.require(:batch).permit(:name, :notes, :multiplier, :concentration, :prep_date)
    end

end

app/helpers/batches_helper.rb
module BatchesHelper
  def converted_recipe_line_item(line_item: recipe_line_item, batch: recipe_batch)
    [line_item.ingredient.name, ' - ', number_with_precision(line_item.calculate_batch_amount(batch), precision: 2), line_item.quantity.unit].join(' ')
  end
end

app/views/batches/_form.html.erb
<%= form_with(model: [@recipe, @batch], local: true ) do |batch_form| %>
  <%= render 'shared/error_messages', object: batch_form.object %>

  <div class="form-group">
    <%= batch_form.label :name %>
    <%= batch_form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= batch_form.label :prep_date %>
    <%= batch_form.date_field :prep_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= batch_form.label :multiplier %>
    <%= batch_form.number_field( :multiplier, min: 0.10, max: 1000.0, step: 0.05, class: 'form-control') %>
  </div>

  <div class="form-group">
    <%= batch_form.label "Concentration % (with decimal)" %>
    <div class="text-muted">E.g. 100.0 or 12.25</div>
    <%= batch_form.number_field :concentration, min: 0.10, max: 200.0, step: 0.05, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= batch_form.label :notes %>
    <%= batch_form.text_area :notes, class: 'form-control', rows: '3' %>
  </div>

  <%= batch_form.submit 'Go', class: 'btn btn-primary' %>

<% end %>

app/views/batches/edit.html.erb
<% provide(:title, 'Edit Batch') %>
<h1>Edit Batch of <%#= @recipe.title %></h1>
<%= render partial: 'form' %>

app/views/batches/index.html.erb
<% provide(:title, 'Recipes') %>
<h3>Batches of your recipes</h3>
<ul>
  <% @recipe.batches.each do |batch| %>
    <li>
      <%= link_to batch.display_name(truncate_by: 50), recipe_batch_path(@recipe, batch) %>
    </li>
  <% end %>
</ul>

app/views/batches/new.html.erb
<% provide(:title, 'New Batch') %>
<h1>New Batch of <%= @recipe.title %></h1>
<%= render partial: 'form' %>

app/views/batches/show.html.erb
<% provide(:title, 'Batch') %>
<h1>Batch of <%= @recipe.title %></h1>
<ul>
  <li>Batch name: <%= @batch.name %></li>
  <li>Preparation date: <%= @batch.date_long %></li>
  <li><strong>Recipe multiplier: <%= @batch.multiplier %></strong></li>
  <li><strong>Recipe concentration %: <%= @batch.concentration %></strong></li>
  <li>Batch preparation notes: <%= @batch.notes %></li>
  <li>Recipe notes: <%= @batch.recipe.description %></li>
  <br>
  <ul>
    <% @recipe.recipe_line_items.each do |recipe_line_item| %>
      <li>
        <%= converted_recipe_line_item(line_item: recipe_line_item, batch: @batch) %>
      </li>
    <% end %>
  </ul>
</ul>
<div><%= link_to('Edit this batch', edit_recipe_batch_path(@recipe, @batch)) %></div>
<div><%= link_to 'View Recipe', recipe_path(@recipe) %></div>
<div><%= link_to 'Delete', recipe_batch_path(@recipe, @batch), method: :delete, data: { confirm: "Are you sure?"} %></div>